// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU7urccdmPWqfL4654wRfk41tuNO4u_XU',
    appId: '1:688287415628:web:9eedfe5dc60891761d23e9',
    messagingSenderId: '688287415628',
    projectId: 'homehaven-c0d5d',
    authDomain: 'homehaven-c0d5d.firebaseapp.com',
    storageBucket: 'homehaven-c0d5d.firebasestorage.app',
    measurementId: 'G-FGGTVSLBFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW6vSOQpnrSRJnB94NkuAolWOsQu4y6P0',
    appId: '1:688287415628:android:38162b32fbeb11801d23e9',
    messagingSenderId: '688287415628',
    projectId: 'homehaven-c0d5d',
    storageBucket: 'homehaven-c0d5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5M1BKTYZA892JCyDCEgQzeMCzlEF9pBQ',
    appId: '1:688287415628:ios:f3ce618942b911c21d23e9',
    messagingSenderId: '688287415628',
    projectId: 'homehaven-c0d5d',
    storageBucket: 'homehaven-c0d5d.firebasestorage.app',
    iosBundleId: 'com.example.furnutureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5M1BKTYZA892JCyDCEgQzeMCzlEF9pBQ',
    appId: '1:688287415628:ios:f3ce618942b911c21d23e9',
    messagingSenderId: '688287415628',
    projectId: 'homehaven-c0d5d',
    storageBucket: 'homehaven-c0d5d.firebasestorage.app',
    iosBundleId: 'com.example.furnutureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU7urccdmPWqfL4654wRfk41tuNO4u_XU',
    appId: '1:688287415628:web:59aa822af8dab0bc1d23e9',
    messagingSenderId: '688287415628',
    projectId: 'homehaven-c0d5d',
    authDomain: 'homehaven-c0d5d.firebaseapp.com',
    storageBucket: 'homehaven-c0d5d.firebasestorage.app',
    measurementId: 'G-M89L2JTNR1',
  );
}
